### Checking the performance of CSV v/s parquet formats

In [22]:
import pandas as pd
from pathlib import Path

DATA_PATH_CSV = Path("../data/processed/equity/master/nse_master_2016_2026.csv")
df = pd.read_csv(DATA_PATH_CSV)
df = df.sort_values(["symbol","trade_date"])
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16

In [23]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/processed/equity/parquet/nse_master_2016_2026.parquet")
df = pd.read_parquet(DATA_PATH)
df = df.sort_values(["symbol","trade_date"])
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16

<b>Note:</b><i>From above example we can see the difference between csv & parquet. That, <b>Parquet is more faster than csv</b></i>

## Daily Return

In [24]:
df["return_1d"] = df.groupby("symbol")["close"].pct_change()
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000

## Short Momentum

In [25]:
df["return_5d"] = df.groupby("symbol")["close"].pct_change(5)
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333

## Medium Momentum

In [26]:
df["return_20d"] = df.groupby("symbol")["close"].pct_change(20)
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN,NaN
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN,NaN
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN,NaN
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514,-0.038462
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316,-0.051282
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316,-0.075000
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316,-0.075000
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333,0.000000

## Rolling Volatility

In [27]:
df["volatility_20d"] = (
    df.groupby("symbol")["return_1d"]
      .rolling(20)
      .std()
      .reset_index(level=0, drop=True)
)
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN,NaN,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN,NaN,NaN
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN,NaN,NaN
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN,NaN,NaN
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514,-0.038462,0.036727
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316,-0.051282,0.036822
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316,-0.075000,0.036251
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316,-0.075000,0.036251
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333,0.000000,0.032081

## Liquidity Features

### Traded Value

In [28]:
df["traded_value"] = df["close"] * df["tottrdqty"]
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN,NaN,NaN,2587833.60
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN,NaN,NaN,9286217.10
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN,NaN,NaN,2633366.25
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN,NaN,NaN,2988485.50
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN,NaN,NaN,1828203.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514,-0.038462,0.036727,251932.50
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316,-0.051282,0.036822,106778.30
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316,-0.075000,0.036251,607166.30
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316,-0.075000,0.036251,209471.80
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333,0.000000,0.032081,675542.30

### Rolling liquidity

In [29]:
df["avg_value_20d"] = (
    df.groupby("symbol")["traded_value"]
      .rolling(20)
      .mean()
      .reset_index(level=0, drop=True)
)
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN,NaN,NaN,2587833.60,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN,NaN,NaN,9286217.10,NaN
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN,NaN,NaN,2633366.25,NaN
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN,NaN,NaN,2988485.50,NaN
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN,NaN,NaN,1828203.30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514,-0.038462,0.036727,251932.50,516479.575
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316,-0.051282,0.036822,106778.30,498582.485
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316,-0.075000,0.036251,607166.30,510020.200
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316,-0.075000,0.036251,209471.80,503989.190
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333,0.000000,0.032081,675542.30,512279.965

## Applying Liquidity Filters

In [30]:
LIQUIDITY_THRESHOLD = 5e7

(₹5 crore average daily traded value)

### Filter dataset:clean tradable universe

In [31]:
df = df[df["avg_value_20d"] > LIQUIDITY_THRESHOLD]
df = df[df["close"] > 20]

### Data after Liquidity Filters

In [32]:
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d
2169246,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,11794,INE144J01027,2021-05-25,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07
2181909,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,5353,INE144J01027,2021-05-26,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07
2194689,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,4367,INE144J01027,2021-05-27,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07
2207322,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,5562,INE144J01027,2021-05-28,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07
2242200,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,2486,INE144J01027,2021-05-31,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4220159,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,3777,INE768C01028,2026-02-24,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07
4222579,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,5789,INE768C01028,2026-02-25,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07
4224997,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,8030,INE768C01028,2026-02-26,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07
4227414,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,10608,INE768C01028,2026-02-27,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07
4229837,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,11663,INE768C01028,2026-03-02,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07

## Relative Strength vs Index

Load index features

In [33]:
path = Path("../data/features/index")

files = sorted(path.glob("index_features_*.parquet"))

index_df = pd.concat(
    [pd.read_parquet(f) for f in files],
    ignore_index=True
)

index_df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d,return_5d,return_20d,volatility_20d,drawdown,volume_change,year
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN,NaN,NaN,NaN,0.000000,NaN,2016
1,NIFTY 50,7589.50,7600.45,7541.25,7555.95,-7.60,-0.10,206645021,8209.50,20.22,3.03,1.53,2016-02-01,-0.051142,NaN,NaN,NaN,-0.051142,NaN,2016
2,NIFTY 50,7038.25,7235.50,7035.10,7222.30,235.25,3.37,283561570,9896.58,19.53,2.90,1.60,2016-03-01,-0.044157,NaN,NaN,NaN,-0.093040,NaN,2016
3,NIFTY 50,7718.05,7740.15,7666.10,7713.05,-25.35,-0.33,189571551,8118.47,21.19,3.26,1.45,2016-04-01,0.067949,NaN,NaN,NaN,-0.031413,NaN,2016
4,NIFTY 50,8179.20,8215.35,8171.05,8179.95,19.85,0.24,200371829,8408.53,22.65,3.41,1.31,2016-06-01,0.060534,NaN,NaN,NaN,0.000000,NaN,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2514,NIFTY 50,25063.35,25246.65,24932.55,25175.40,126.75,0.51,618696080,50989.25,21.91,3.42,1.33,2026-01-27,-0.012596,0.005060,-0.023840,0.009998,-0.043798,0.570514,2026
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27,0.000129,-0.020781,-0.024356,0.009994,-0.043675,0.099686,2026
2516,NIFTY 50,25258.85,25372.10,25187.65,25342.75,167.35,0.66,574903942,42364.52,22.07,3.45,1.30,2026-01-28,0.006517,-0.003221,-0.015139,0.010130,-0.037442,0.309373,2026
2517,NIFTY 50,25345.00,25458.15,25159.80,25418.90,76.15,0.30,582389331,44306.95,22.12,3.46,1.30,2026-01-29,0.003005,-0.002496,-0.002049,0.009909,-0.034550,0.406005,2026
2518,NIFTY 50,25247.55,25370.70,25213.65,25320.65,-98.25,-0.39,508388604,40772.08,22.04,3.44,1.30,2026-01-30,-0.003865,-0.006899,-0.013440,0.009772,-0.038282,0.254601,2026

Merging equity & index features

In [34]:
df = df.merge(
    index_df[["trade_date","return_1d"]],
    on="trade_date",
    suffixes=("","_index")
)

Merged Data

In [35]:
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,11794,INE144J01027,2021-05-25,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.061679
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,5353,INE144J01027,2021-05-26,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.056365
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,4367,INE144J01027,2021-05-27,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.046734
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,5562,INE144J01027,2021-05-28,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.038420
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,2486,INE144J01027,2021-05-31,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.060725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,3777,INE768C01028,2026-02-24,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,5789,INE768C01028,2026-02-25,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,8030,INE768C01028,2026-02-26,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,10608,INE768C01028,2026-02-27,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,0.000129
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,11663,INE768C01028,2026-03-02,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.008877

### Compute relative strength

In [36]:
df["relative_strength"] = df["return_1d"] - df["return_1d_index"]
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,...,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index,relative_strength
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,...,INE144J01027,2021-05-25,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.061679,-4.647294e-02
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,...,INE144J01027,2021-05-26,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.056365,-8.132954e-02
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,...,INE144J01027,2021-05-27,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.046734,-4.966041e-02
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,...,INE144J01027,2021-05-28,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.038420,-1.044511e-01
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,...,INE144J01027,2021-05-31,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.060725,-5.365558e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,...,INE768C01028,2026-02-24,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214,-7.598075e-03
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,...,INE768C01028,2026-02-25,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275,-1.555856e-02
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,...,INE768C01028,2026-02-26,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551,-2.303040e-02
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,...,INE768C01028,2026-02-27,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,0.000129,8.264738e-07
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,...,INE768C01028,2026-03-02,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.008877,-6.581948e-03

## Cross-Sectional Ranking

daily ranking across stocks

In [37]:
df["rank_momentum"] = (
    df.groupby("trade_date")["return_20d"]
      .rank(ascending=False)
)

In [38]:
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,...,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index,relative_strength,rank_momentum
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,...,2021-05-25,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.061679,-4.647294e-02,3.0
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,...,2021-05-26,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.056365,-8.132954e-02,3.0
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,...,2021-05-27,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.046734,-4.966041e-02,4.0
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,...,2021-05-28,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.038420,-1.044511e-01,8.0
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,...,2021-05-31,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.060725,-5.365558e-02,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,...,2026-02-24,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214,-7.598075e-03,874.0
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,...,2026-02-25,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275,-1.555856e-02,930.0
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,...,2026-02-26,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551,-2.303040e-02,1010.0
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,...,2026-02-27,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,0.000129,8.264738e-07,1013.0
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,...,2026-03-02,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.008877,-6.581948e-03,984.0

Normalize ranking

In [39]:
df["rank_pct"] = (
    df.groupby("trade_date")["return_20d"]
      .rank(pct=True)
)

In [40]:
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,...,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index,relative_strength,rank_momentum,rank_pct
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,...,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.061679,-4.647294e-02,3.0,0.997187
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,...,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.056365,-8.132954e-02,3.0,0.997211
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,...,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.046734,-4.966041e-02,4.0,0.995868
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,...,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.038420,-1.044511e-01,8.0,0.990437
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,...,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.060725,-5.365558e-02,9.0,0.989218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,...,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214,-7.598075e-03,874.0,0.210669
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,...,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275,-1.555856e-02,930.0,0.153145
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,...,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551,-2.303040e-02,1010.0,0.076853
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,...,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,0.000129,8.264738e-07,1013.0,0.073260
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,...,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.008877,-6.581948e-03,984.0,0.099817

Normally ranking: Pandas converts ranks into percentiles</br>
Percentile Rank = Rank / Total Stocks</br>
| Stock   | return_20d | rank | rank_pct |
| ------- | ---------- | ---- | -------- |
| Stock A | 0.50       | 1    | 0.001    |
| Stock B | 0.45       | 50   | 0.05     |
| Stock C | 0.10       | 500  | 0.50     |
| Stock D | -0.30      | 1000 | 1.00     |
<hr>
0.05 → top 5% momentum stock</br>
0.50 → average stock</br>
1.00 → worst momentum stock

## Save Features (Partitioned Parquet)

In [41]:
df["year"] = df["trade_date"].dt.year
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,...,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index,relative_strength,rank_momentum,rank_pct,year
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,...,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.061679,-4.647294e-02,3.0,0.997187,2021
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,...,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.056365,-8.132954e-02,3.0,0.997211,2021
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,...,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.046734,-4.966041e-02,4.0,0.995868,2021
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,...,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.038420,-1.044511e-01,8.0,0.990437,2021
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,...,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.060725,-5.365558e-02,9.0,0.989218,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,...,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214,-7.598075e-03,874.0,0.210669,2026
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,...,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275,-1.555856e-02,930.0,0.153145,2026
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,...,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551,-2.303040e-02,1010.0,0.076853,2026
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,...,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,0.000129,8.264738e-07,1013.0,0.073260,2026
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,...,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.008877,-6.581948e-03,984.0,0.099817,2026

In [42]:
output_path = Path("../data/features/equity")

if not output_path.exists():
    output_path.mkdir(parents=True, exist_ok=True)

years = df["year"].unique()

for year in years:
    
    df_year = df[df["year"] == year]
    
    file_path = output_path / f"equity_features_{year}.parquet"
    
    if not file_path.exists():
        df_year.to_parquet(file_path, index=False)